name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

# Prevent parallel runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv pip install ".[dev]"

      # Cache pip for Python hook installs
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Run pre-commit in check-only mode (fail on any diffs)
      - name: Run pre-commit (check-only)
        uses: pre-commit/action@v3.0.1
        with:
          args: run --all-files --show-diff-on-failure